-- WRITEWISE ONE-TIME SUPABASE SETUP
-- 1. Replace Moazzam2026@WriteWise#987654321 everywhere below with a long private secret.
-- 2. Run this complete file once in Supabase → SQL Editor.

create extension if not exists pgcrypto;

create table if not exists public.submissions (
  id uuid primary key default gen_random_uuid(),
  access_code text unique not null,
  customer_name text not null check (char_length(customer_name) between 2 and 60),
  customer_note text default '',
  image_path text not null,
  status text not null default 'pending_review' check (status in ('pending_review','completed')),
  report_text text default '',
  created_at timestamptz not null default now(),
  reviewed_at timestamptz
);

alter table public.submissions enable row level security;
revoke all on public.submissions from anon, authenticated;

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values ('handwriting', 'handwriting', true, 5242880, array['image/jpeg','image/png','image/webp'])
on conflict (id) do update set public = true, file_size_limit = 5242880,
allowed_mime_types = array['image/jpeg','image/png','image/webp'];

-- Upload permission. Filenames are long random UUIDs generated by the app.
drop policy if exists "writewise anonymous uploads" on storage.objects;
create policy "writewise anonymous uploads" on storage.objects
for insert to anon with check (bucket_id = 'handwriting');

create or replace function public.create_submission(
  p_access_code text,
  p_customer_name text,
  p_customer_note text,
  p_image_path text
) returns uuid
language plpgsql security definer set search_path = public
as $$
declare new_id uuid;
begin
  if char_length(trim(p_access_code)) < 8 then raise exception 'Invalid access code'; end if;
  insert into submissions(access_code, customer_name, customer_note, image_path)
  values (trim(p_access_code), trim(p_customer_name), left(coalesce(p_customer_note,''),500), p_image_path)
  returning id into new_id;
  return new_id;
end; $$;

create or replace function public.customer_submissions(p_access_code text)
returns table(id uuid, customer_name text, customer_note text, image_path text, status text,
              report_text text, created_at timestamptz, reviewed_at timestamptz)
language sql security definer set search_path = public
as $$
  select s.id,s.customer_name,s.customer_note,s.image_path,s.status,s.report_text,s.created_at,s.reviewed_at
  from submissions s where s.access_code = trim(p_access_code)
  order by s.created_at desc;
$$;

create or replace function public.admin_submissions(p_admin_key text)
returns table(id uuid, access_code text, customer_name text, customer_note text, image_path text,
              status text, report_text text, created_at timestamptz, reviewed_at timestamptz)
language plpgsql security definer set search_path = public
as $$
begin
  if p_admin_key <> 'Moazzam2026@WriteWise#987654321' then raise exception 'Unauthorized'; end if;
  return query select s.id,s.access_code,s.customer_name,s.customer_note,s.image_path,s.status,
    s.report_text,s.created_at,s.reviewed_at from submissions s order by s.created_at desc;
end; $$;

create or replace function public.publish_report(p_admin_key text, p_id uuid, p_report text)
returns boolean language plpgsql security definer set search_path = public
as $$
begin
  if p_admin_key <> 'Moazzam2026@WriteWise#987654321' then raise exception 'Unauthorized'; end if;
  if char_length(trim(p_report)) < 40 then raise exception 'Report too short'; end if;
  update submissions set report_text=trim(p_report),status='completed',reviewed_at=now() where id=p_id;
  return found;
end; $$;

create or replace function public.delete_submission(p_admin_key text, p_id uuid)
returns text language plpgsql security definer set search_path = public
as $$
declare old_path text;
begin
  if p_admin_key <> 'Moazzam2026@WriteWise#987654321' then raise exception 'Unauthorized'; end if;
  delete from submissions where id=p_id returning image_path into old_path;
  return old_path;
end; $$;

grant execute on function public.create_submission(text,text,text,text) to anon;
grant execute on function public.customer_submissions(text) to anon;
grant execute on function public.admin_submissions(text) to anon;
grant execute on function public.publish_report(text,uuid,text) to anon;
grant execute on function public.delete_submission(text,uuid) to anon;
